### PR TITLE
[#22] Implement retry queue and add retry limit

### PR DESCRIPTION
**Pull request by konstk1**
Fixes issue #22

### CODE REVIEW

**Comment by konstk1** [comment]
Note that I couldn't thoroughly test this because oauthbin.com doesn't seem to exist anymore.  I run some other tests by mocking the interceptor to verify logic works.

**Comment by phimage** [comment]
thanks for the PR and the last commit
I do not know when PR
If you want I could merge now but you must do another PR when finally Alamofire will do a real release ...

**Comment by konstk1** [comment]
I think the last commit does not specify the dependency requirements correctly.  Let me fix that first.

**Comment by phimage** [comment]
yes maybe for carthage too

**Comment by konstk1** [comment]
Ok, should be good to merge now. I'll issue another PR when Alamofire 5.0 is released.

Any idea what happened to oauthbin.com?

**Comment by phimage** [comment]
maybe down
I am looking for alternative
https://code-examples.net/en/q/35c905 maybe http://term.ie/oauth/example/index.php

**Comment by phimage** [comment]
I make a new pr, updating carthage and travis file without a macOS so I do not really see the code running ut if this could help
https://travis-ci.org/OAuthSwift/OAuthSwiftAlamofire/jobs/581809211

**Pull request merged**
